<div id="location-bar">
    <div class="sized-layout">
        Greenwich, CT &nbsp;|&nbsp; New York &nbsp;|&nbsp;

        <a class="fb-icon-location-bar"
           href="http://www.facebook.com/#!/pages/Roughan-Interior-Design/161295963887785" target="_blank" title="Roughan Interior Design On Facebook"></a>
		   <a class="pin-icon-location-bar"
           href="http://pinterest.com/roughanid/" target="_blank" title="Roughan Interior Design On Pinterest"></a>
        
    </div>
</div>

<div id="header">
    <div class="sized-layout">
        <div id="header-logo"><a href="/"></a></div>
        <div id="header-nav">
            <ul>
                <li><a href="/content/projects">Projects</a></li>
                <li class="expando">
                    <a href="#" class="expando-link">About</a>

                    <div class="expando-panel">
                        <a href="/content/about/">Christina Sullivan Roughan</a>
                        <div style="height:1px;background:#c1beb3;margin:3px 0 3px 0;"></div>
                        <a href="/content/about/roughan.html">Roughan Interior Design</a>
                    </div>
                </li>
                <li><a href="/content/press">Press</a></li>
                <li><a href="/content/contact">Contact</a></li>
				<li><a href="http://homegarden.over40females.com/" target="blank">Blog</a></li>
				<li><a href="http://decoratortagsale.com/designer-view/?d=2120">Boutique</a></li>
            </ul>

        </div>
        <div class="clear"></div>
    </div>
</div>